apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  statusbadge.enabled: "true"
  accounts.team-product: login
  accounts.provider-argocd: apiKey
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - kube-controller-manager
    jqPathExpressions:
      - '.webhooks[]?.failurePolicy'
