apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  accounts.team-product: login
  statusbadge.enabled: "true"
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - kube-controller-manager
      - rollouts-controller
    jsonPointers:
      - /spec/replicas
      - /spec/tls
      - /spec/http
    jqPathExpressions:
      - '.webhooks[]?.failurePolicy'
