apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:read, applications, get, */*, allow
    p, role:read, clusters, get, *, allow
    p, role:read, repositories, get, *, allow
    p, role:read, gpgkeys, get, *, allow
    g, read, role:read

    p, role:sync, applications, get, */*, allow
    p, role:sync, applications, sync, */*, allow
    p, role:sync, clusters, get, *, allow
    p, role:sync, repositories, get, *, allow
    p, role:sync, gpgkeys, get, *, allow
    g, sync, role:sync

    p, role:project, applications, get, team-product/*, allow
    p, role:project, applications, sync, team-product/*, allow
    g, project, role:project
    g, project, role:read
  policy.default: role:''
