name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version Tag"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Update version in manifest
        run: |
          echo "Deploy tag: ${{ github.event.inputs.tag }}"
          
          yq -i '.spec.source.helm.parameters |= map(select(.name == "*image.tag").value="${{TAG}}")' ./argo/environments/${{ENV_NAME}}/${{SQUAD_OWNER}}/${{CF_REPO_NAME}}/${{REGION}}/argo-application.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "release: ${{ github.event.inputs.tag }}"
