apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-product
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team-product
  destination:
    server: https://kubernetes.default.svc
    namespace: product
  source:
    path: projects/root/teams/team-product
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
