apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-product
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: team-product project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "product"
      server: "*"
  roles:
    # A role which provides operator access to all applications in the project
    - name: operator
      description: Operator privileges to team-product
      policies:
        - p, proj:team-product:operator, *, *, */*, allow
        - p, proj:team-product:operator, *, delete, */*, deny
      groups:
        - team-product
