apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    istio-injection: enabled
    config-syncer-commons-config: enabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
