apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: 3rd
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  source:
    path: apps/3rd/istio/d
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
