apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 3rd
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  source:
    path: apps/3rd/istio/ingress-gateway
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
