apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-api
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dtelaroli/argocd-test.git
        revision: main
        files:
          - path: environments/**/config.yaml
  template:
    metadata:
      name: "product-api-{{env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: team-product
      source:
        repoURL: https://github.com/dtelaroli/argocd-test.git
        path: apps/teams/team-product/api
        targetRevision: main
        helm:
          # version: v3
          # valueFiles:
          #   - values.yaml
          parameters:
            - name: "canary.environment"
              value: "{{env}}"
            - name: "canary.version"
              value: "1.5.0"

      destination:
        server: "{{url}}"
        namespace: product
      syncPolicy:
        syncOptions:
          - FailOnSharedResource=true
