apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: teams
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: projects/root/teams
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
