apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teams
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: teams project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: "*"
      server: "*"
