apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.application }}
spec:
  host: {{ .Values.application }}
  subsets:
    - name: stable
      labels:
        mydomain.com/app: {{ .Values.application }}
    - name: canary
      labels:
        mydomain.com/app: {{ .Values.application }}
