apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.application }}
spec:
  gateways:
    - istio-gateways/public
  hosts:
    - {{ .Values.application }}.mydomain.com
  http:
    - name: primary
      route:
        - destination:
            host: {{ .Values.application }}
            subset: stable
          weight: 100
        - destination:
            host: {{ .Values.application }}
            subset: canary
          weight: 0
  tls:
    - match:
        - port: 443
          sniHosts:
            - {{ .Values.application }}.mydomain.com
      route:
        - destination:
            host: {{ .Values.application }}
            subset: stable
          weight: 100
        - destination:
            host: {{ .Values.application }}
            subset: canary
          weight: 0
