apiVersion: v1
kind: Namespace
metadata:
  name: product
  labels:
    name: product
    istio-injection: enabled
    config-syncer-commons-config: enabled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
