apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - env: dev
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "argo-rollouts-{{env}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 3rd
      source:
        repoURL: https://github.com/dtelaroli/argocd-test.git
        path: apps/3rd/argo-rollouts
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argo-rollouts
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
