apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/dtelaroli/argocd-test.git
        revision: main
        files:
          - path: environments/**/config.yaml
  template:
    metadata:
      name: "argo-rollouts-{{ env }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 3rd
      source:
        repoURL: https://github.com/dtelaroli/argocd-test.git
        path: apps/3rd/argo-rollouts
        targetRevision: HEAD
      destination:
        server: "{{ url }}"
        namespace: argo-rollouts
      syncPolicy:
        # automated:
        #   selfHeal: true
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
