apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 3rd
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  source:
    path: apps/3rd/istio/base
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/*/failurePolicy