apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: my-strange-canary
  namespace: product
  labels:
    app.kubernetes.io/instance: product-api-dev
spec:
  # Duration of the experiment, beginning from when all ReplicaSets became healthy (optional)
  # If omitted, will run indefinitely until terminated, or until all analyses which were marked
  # `requiredForCompletion` have completed.
  # duration: 20m

  # Deadline in seconds in which a ReplicaSet should make progress towards becoming available.
  # If exceeded, the Experiment will fail.
  # progressDeadlineSeconds: 90

  # List of pod template specs to run in the experiment as ReplicaSets
  templates:
  - name: guestbook-strange-canary
    # Number of replicas to run (optional). If omitted, will run a single replica
    replicas: 1
    # Flag to create Service for this Experiment (optional)
    # If omitted, a Service won't be created.
    service:
      # Name of the Service (optional). If omitted, service: {} would also be acceptable.
      name: guestbook-strange-canary
    selector:
      matchLabels:
        app.kubernetes.io/name: guestbook-strange-canary
    template:
      metadata:
        annotations:
          proxy.istio.io/config: |
            terminationDrainDuration: 30s
          sidecar.istio.io/inject: 'true'
          sidecar.istio.io/rewriteAppHTTPProbers: 'true'
        labels:
          app: guestbook-strange-canary
          app.kubernetes.io/name: guestbook-strange-canary
          fullname: guestbook-1.16.2
          squad: psm-test
          version: 1.16.2
      spec:
        containers:
          - image: 'istio/examples-bookinfo-productpage-v1:1.16.2'
            imagePullPolicy: Always
            name: guestbook-strange-canary
            ports:
              - containerPort: 9080
                name: http
                protocol: TCP
