apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      guestbook.mydomain.com/app: guestbook-ui
  template:
    metadata:
      labels:
        guestbook.mydomain.com/app: guestbook-ui
        guestbook.mydomain.com/version: "1.8.0"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: istio/examples-bookinfo-productpage-v1:1.8.0
          name: guestbook-ui
          ports:
            - containerPort: 9080
              protocol: TCP
  strategy:
    canary:
      stableMetadata:
        labels:
          argo-rollouts/version: stable
      canaryMetadata:
        labels:
          argo-rollouts/version: canary
      steps:
        - setHeaderRoute:
            name: header-version
            match:
              - headerName: x-version
                headerValue:
                  exact: "1.8.0"
        - setWeight: 10
        - pause:
            duration: 30s
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 30
        - pause:
            duration: 30s
        - setWeight: 40
        - pause:
            duration: 30s
        - setWeight: 80
        - pause:
            duration: 30s
        - setWeight: 100
        - pause:
            duration: 10s
      trafficRouting:
        managedRoutes:
          - name: header-version
        istio:
          virtualService:
            name: guestbook-ui
            routes:
              - primary
          destinationRule:
            name: guestbook-ui
            stableSubsetName: stable
            canarySubsetName: canary
