apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: guestbook-ui
spec:
  gateways:
    - istio-gateways/public
  hosts:
    - guestbook.mydomain.com
  http:
    - name: primary
      route:
        - destination:
            host: guestbook-ui
            subset: stable
          weight: 100
        - destination:
            host: guestbook-ui
            subset: canary
          weight: 0
  tls:
    - match:
        - port: 443
          sniHosts:
            - guestbook.mydomain.com
      route:
        - destination:
            host: guestbook-ui
            subset: stable
          weight: 100
        - destination:
            host: guestbook-ui
            subset: canary
          weight: 0
