apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateways
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: 3rd
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-gateways
  source:
    path: apps/3rd/istio/gateways
    repoURL: https://github.com/dtelaroli/argocd-test.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
