name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version Tag"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update version in manifest
        run: |
          echo "Deploy tag: ${{ github.event.inputs.tag }}"
          yq -i '.canary.version = "${{ github.event.inputs.tag }}"' apps/teams/team-product/api/values.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "release: ${{ github.event.inputs.tag }}"
